### ISSUE TITLE
AI Core Setup - wrong/too many roles

### ISSUE THREAD

**Issue by lechnerc77** [SAP-docs/sap-artificial-intelligence#14]
### Issue description

Editorial remark: there are two dots at the end of step 2

Content: Why are all roles needed. I would assume that at least the space auditor role is not needed?

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Create a Space

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-space?version=CLOUD

**Comment by karu-0711** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by karu-0711** [comment]
Thanks again for your feedback. We have updated our documentation and you should see the revised content on SAP Help Portal soon.
