### ISSUE TITLE
AI Core Setup - missing parameters

### ISSUE THREAD

**Issue by lechnerc77** [SAP-docs/sap-artificial-intelligence#15]
### Issue description

Step 4 describes that there are optional parameters. However, there is no information available about the parameters and what the user can configure when adding them.

If the user should provide a JSON this and in addition a JSON schema would be needed.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Create a Service Instance

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/create-service-instance?version=CLOUD

**Comment by karu-0711** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by karu-0711** [comment]
Thanks again for bringing this to our attention. Our development team has informed us that currently SAP AI Core doesn't support additional parameters when deploying a service instance. We have updated our content accordingly and a correction will be available on SAP Help Portal soon.
