### ISSUE TITLE
AI Core Setup - availability of curl

### ISSUE THREAD

**Issue by lechnerc77** [SAP-docs/sap-artificial-intelligence#16]
### Issue description

The description in the section [Using curl](https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/use-service-key?version=CLOUD#using-curl) is targeting Mac users only. 

Curl is also available for PowerShell i.e. on Windows. However, the description namely the export will only work on Mac or Linux. A Windows specific section should be added.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Use a Service Key

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/use-service-key?version=CLOUD

**Comment by karu-0711** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by karu-0711** [comment]
Hi Christian. We've now added some information about PowerShell to the curl section. Thanks again for bringing this to our attention.
