### ISSUE TITLE
Unclear wording on the GenAI hub metering page

### ISSUE THREAD

**Issue by sagarwal88** [SAP-docs/sap-artificial-intelligence#19]
### Issue description

Hi,

There is a statement written on the page where it says - "**A GenAI token corresponds to a block of 1,000 tokens from the LLM service provider. Its cost varies depending on the model used and the type of token (input or output).**"

This is somewhat confusing. Could you elaborate on this further. To me it sounds like 1 GenAI token on SAP BTP will give access to 1000 tokens from the LLM service provider (such as Azure Open AI).

If this is the case (or otherwise), if you can elaborate on this further it will be helpful for anyone who reads the documentation.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Metering and Pricing for the Generative AI Hub

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/metering-and-pricing-for-generative-ai-hub

**Comment by helenaaaaaaaaaa** [comment]
Thankyou for your feedback, we are making updates to this page. If you have further questions after the changes have been made, please let me know.
