### ISSUE TITLE
API URL to Gemini 1.0 Pro has an incorrect endpoint

### ISSUE THREAD

**Issue by Jelena-P** [SAP-docs/sap-artificial-intelligence#22]
### Issue description

The API URL to Gemini 1.0 Pro has an incorrect endpoint. It should be
 
'$DEPLOYMENT_URL/models/gemini-1.0-pro:generateContent' 

instead of 

'$DEPLOYMENT_URL/chat/models/gemini-1.0-pro:generateContent.

Reported here: https://www.linkedin.com/posts/abesh_if-you-are-using-googles-gemini-pro-on-sap-activity-7191242993553571841-dP0x

### Feedback Type (Optional)

incorrect statement

### Page Title on SAP Help Portal (prefilled)

Consume Generative AI Models

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/consume-generative-ai-models-using-sap-ai-core

**Comment by helenaaaaaaaaaa** [comment]
Thankyou for your contribution, we'll look into it and come back to you if we need more information.

**Comment by karu-0711** [comment]
Hi @Jelena-P. Thank you for bringing this to our attention. We have now published a corrected version of the code.
