### ISSUE TITLE
Add info how to increase rate limits.

### ISSUE THREAD

**Issue by karimmohraz** [SAP-docs/sap-artificial-intelligence#24]
### Issue description

The SAP note for token price and in rate limits is referenced in this help page.
Plz add info how to raise the rate limits. Either in this help page or the SAP note.

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Models and Scenarios in the Generative AI Hub

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/sap-ai-core/sap-ai-core-service-guide/models-and-scenarios-in-generative-ai-hub

**Comment by helenaaaaaaaaaa** [comment]
This has been included in the most recent release.

**Comment by karimmohraz** [comment]
7286


From: sap-doc-bot[bot] ***@***.***>
Date: Thursday, 23. May 2024 at 15:57
To: SAP-docs/sap-artificial-intelligence ***@***.***>
Cc: Mohraz, Karim ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/sap-artificial-intelligence] Add info how to increase rate limits. (Issue #24)

Thank you for your valuable feedback contribution, @karimmohraz<https://github.com/karimmohraz>! So that we can recognize your contribution in the SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please check your SAP Community user ID (this is a number) in your personal settings page<https://community.sap.com/t5/user/myprofilepage/tab/personal-profile> and share it with us in a reply to this comment. Make sure you just include the number in the reply.

Your user ID is displayed as follows:

Change display name for User ID N

where N is your user ID. For example, 53 is the user ID of the user 'qmacro'<https://community.sap.com/t5/user/viewprofilepage/user-id/53>.

Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.
