### ISSUE TITLE
Feedback for "Terminology"

### ISSUE THREAD

**Issue by sebbae** [SAP-docs/sap-artificial-intelligence#4]
https://help.sap.com/docs/ai-launchpad/sap-ai-launchpad/terminology

There is an oopsie in the _Executable_ section where the term _Templates_ is present twice:

"For more information, see [Templates](https://help.sap.com/viewer/2d6c5984063c40a59eda62f4a9135bee/CLOUD/en-US/8a1f91a18cf0473e8689789f1636675a.html), [Executables](https://help.sap.com/docs/ai-launchpad/sap-ai-launchpad/executables), or [Templates](https://help.sap.com/docs/ai-launchpad/sap-ai-launchpad/templates)."

Also, the first _Templates_ link points to a  `Sorry We couldn't find that page.` error page

**Comment by karu-0711** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by karu-0711** [comment]
Thanks again for your input. We've fixed the documentation and the correction will appear on SAP Help Portal soon.
